my_list= []
my_list.append(10)
print(my_list)
my_list.append(20)
print(my_list)
my_list.append(30)
print(my_list)
my_list.append(40)
print(my_list)
my_list.insert(1,15)
print(my_list)
my_list.extend([60,50,70])
print(my_list)
my_list.pop(-1)
print(my_list)
my_list.sort()
print(my_list)
pos_no_30 = my_list.index(30)
print(pos_no_30)